# Generated by Django 6.0.1 on 2026-02-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_transcriptchunk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcriptsegment',
            name='transcript',
        ),
        migrations.AddField(
            model_name='transcript',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='TranscriptChunk',
        ),
        migrations.DeleteModel(
            name='TranscriptSegment',
        ),
    ]
